add project spec notebook
joelostblom/datacamp-projects pull request #1
Opened 2018-06-15 16:46 UTC by aays

2018-06-22 13:11 UTC, joelostblom requested changes
Looks great overall! Let me know what you think of the suggestions I made and sorry for not getting to this earlier.

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "**Link to prior writing**: Please supply a link/reference to some of your own already published educational writing. For example, in the form of a blog post, notebook, article, book or internal
We can add a link to our lecture folder here, or maybe selected lectures that one of us has authored. Or just link the workshop material we did last week, that's maybe easier.

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "**E-mail:** A DataCamp connected e-mail (connected in the sense that you could use it to log in to datacamp.com).\n",
Add all our emails here, the one I use for datacamp is joel.ostblom@gmail.com. @linamnt and @mbonsma, which are yours?

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "> Using a subset of the dataset comprised of two genres (Hip-Hop and Rock), we will train a classifier to distinguish between the two genres based only on track infromation derived from Echonest
infromation -> information

Last sentence: I think we will only use PCA, logistic regression and decision trees.

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "TODO: add links to datasets - these can be links to GitHub uploads\n",
Is this TODO for our subsetted data sets? you already have a link to the main repo.

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "> The student knows how to read in csv and json files using `pandas`, and examine correlations across the columns of a `pandas` DataFrame. The student understands basic plotting (scatter plots,
Suggestion for the last sentence:

The student is also familiar with implementing principal component analysis, supervised learning methods (decision trees and logistic regression), and model accuracy scoring using k-fold crossvalidation and  the classification report in scikit-learn.

@linamnt Do we want to talk about precision and recall and plot the curves in the final version?

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "## These recommendations are so on point! How does this playlist know me so well?\n",
Nice intro blurb!

2018-06-22 13:11 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "track_metrics = pd.read_json('./echonest-clean.json', precise_float=True)\n",
We should either mention or remove `precise_float`, I don't think they would know to use it here.

2018-06-22 13:15 UTC, joelostblom commented on fma_project_spec.ipynb
> +    "TODO: add links to datasets - these can be links to GitHub uploads\n",
I create a link for our data sets https://www.dropbox.com/sh/bab3yu27thfcv45/AAAHoBux36O54Dyg6UUOBv_8a?dl=0

2018-06-22 15:26 UTC, linamnt commented on fma_project_spec.ipynb
> +    "> The student knows how to read in csv and json files using `pandas`, and examine correlations across the columns of a `pandas` DataFrame. The student understands basic plotting (scatter plots,
I think this is pretty useful on the grand scheme of ML so I lean towarads yes. If it feels like there's too much it's easily mentionable without plotting/going in depth

2018-06-24 23:12 UTC, aays commented on fma_project_spec.ipynb
> +    "**Link to prior writing**: Please supply a link/reference to some of your own already published educational writing. For example, in the form of a blog post, notebook, article, book or internal
I just pulled up various Coders/R Course lessons for this - 

[Lina](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/classes/Classes_in_Python.ipynb), [Joel](https://github.com/UofTCoders/rcourse/blob/master/lec02-basic-r.Rmd), [Madeleine](https://github.com/UofTCoders/rcourse/blob/master/lec07-pop-models.Rmd), [Ahmed](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/r/dplyrmagrittr/lesson.Rmd)

2018-06-24 23:12 UTC, aays commented on fma_project_spec.ipynb
> +    "**E-mail:** A DataCamp connected e-mail (connected in the sense that you could use it to log in to datacamp.com).\n",
All good - nabbed these from our email thread with David!

2018-06-24 23:16 UTC, aays commented
@joelostblom I've updated the notebook to reflect all of the above feedback, save for the `precise_float` bit - are we mentioning it or removing it?

2018-06-26 00:16 UTC, joelostblom commented
Great, thanks @aays ! Let's remove `precise_float` for now, and decide wether to add it back in for the  final version.

We should be good to hit submit now then? @linamnt Do you want to email this Maddy's to David?

2018-06-26 00:16 UTC, joelostblom approved these changes

2018-06-26 00:17 UTC, merged